# Generated by Django 3.2 on 2021-04-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_alter_author_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usefulness',
            name='Comment',
        ),
        migrations.AddField(
            model_name='usefulness',
            name='Score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book'),
        ),
        migrations.AlterField(
            model_name='usefulness',
            name='CommentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.comments'),
        ),
    ]
