# Generated by Django 3.2 on 2021-04-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20210427_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.FloatField(),
        ),
    ]
