# Generated by Django 3.2 on 2021-04-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_order_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trustfactor',
            unique_together={('UsernameGiver', 'UsernameReceiver')},
        ),
    ]
