# Generated by Django 3.2 on 2021-04-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_alter_usefulness_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usefulness',
            unique_together={('Username', 'CommentId')},
        ),
    ]
