# Generated by Django 3.2 on 2021-04-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20210408_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
