# Generated by Django 3.2 on 2021-04-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20210408_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentId', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=255)),
                ('Comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=255)),
                ('Amount', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrustFactor',
            fields=[
                ('TrustId', models.AutoField(primary_key=True, serialize=False)),
                ('UsernameGiver', models.CharField(max_length=255)),
                ('UsernameReceiver', models.CharField(max_length=255)),
                ('Score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usefulness',
            fields=[
                ('UsefulnessId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('CommentId', models.IntegerField()),
                ('Comment', models.TextField()),
            ],
        ),
    ]
