# Generated by Django 3.2 on 2021-04-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_comments_order_trustfactor_usefulness'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('ISBN', 'Username')},
        ),
    ]
