# Generated by Django 3.2 on 2021-04-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_comments_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book'),
        ),
    ]
