# Generated by Django 3.2 on 2021-04-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_alter_order_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book'),
        ),
    ]
