# Generated by Django 3.2 on 2021-04-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_alter_usefulness_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usefulness',
            unique_together=set(),
        ),
    ]
